version: '3.8'
services:

  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: shareit_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build: server/
    image: shareit_server
    container_name: shareit_server
    ports:
      - "8090:8090"
      - "8091:8091"
    depends_on:
      - db
    environment:
#      - TZ=Europe/Moscow
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  gateway:
    build: gateway/
    image: shareit_gateway
    container_name: shareit_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - server
    environment:
#      - TZ=Europe/Moscow
      - SHAREIT_SERVER_URL=http://localhost:8090

